<div class="content-box">
<div class="content-box-content">
<h1><?php echo $this->__('FAQ overview'); ?></h1>
<?php if ($this->hasFaq()): ?>
<ul class="faq-list">
	<?php foreach ($this->getFaqCollection() as $faqItem): ?>
	<li>
		<a href="#faq-item-<?php echo $faqItem->getId() ?>"><?php echo $this->htmlEscape($faqItem->getQuestion()) ?></a>
	</li>
	<?php endforeach; ?>
</ul>	
<dl class="faq-items">
	<?php foreach ($this->getFaqCollection() as $faqItem): ?>
	<dt id="faq-item-<?php echo $faqItem->getId() ?>">
		<?php echo $this->htmlEscape($faqItem->getQuestion()) ?>
	</dt>
	<dd>
		<?php echo ($faqItem->getAnswerHtml() ? $faqItem->getAnswer() : '<p>'.implode('</p><p>', explode("\n", $this->htmlEscape($faqItem->getAnswer())))) ?>
	</dd>
	<?php endforeach; ?>
</dl>
<?php else: ?>
<p class="faq-items"><?php echo $this->__('There are no FAQ items at the moment.') ?></p>
<?php endif; ?>
</div>
<div class="content-box-footer"></div>
</div>